# Generated by Django 3.0.1 on 2019-12-29 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objectives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation.')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Time of modification.')),
                ('stem', models.TextField(help_text='The basic question stem.')),
                ('contributor', models.ForeignKey(help_text='The user who contributed this question.', on_delete=django.db.models.deletion.PROTECT, related_name='user_question', to=settings.AUTH_USER_MODEL)),
                ('objective', models.ForeignKey(help_text='The parent learning objective for this question.', on_delete=django.db.models.deletion.PROTECT, related_name='objective_question', to='objectives.Objective')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text displayed for this choice under a question.')),
                ('explanation', models.TextField(help_text='The explanation for why this chocie is right or wrong.')),
                ('is_correct', models.BooleanField(help_text='Whether this is the correct choice, or an incorrect choice.')),
                ('question', models.ForeignKey(help_text='The parent question to which this choice belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='question_choice', to='questions.Question')),
            ],
            options={
                'unique_together': {('question', 'content')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time the response was submitted.')),
                ('choice', models.ForeignKey(help_text='The choice which was selected for this response.', on_delete=django.db.models.deletion.CASCADE, related_name='choice_response', to='questions.QuestionChoice')),
                ('user', models.ForeignKey(blank=True, help_text='Optional user who sent the response. If null, assume to be anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='An integer rating in the range 1-5 inclusive.')),
                ('question', models.ForeignKey(help_text='The question that was rated', on_delete=django.db.models.deletion.CASCADE, related_name='question_rating', to='questions.Question')),
                ('user', models.ForeignKey(blank=True, help_text='The user who rated the question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time the comment was posted.')),
                ('content', models.TextField(help_text='The comment iself, stored as Markdown.')),
                ('contributor', models.ForeignKey(blank=True, help_text='The optional user who authored the comment. If null, it is anonymous.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(help_text='The question that was commented on.', on_delete=django.db.models.deletion.CASCADE, related_name='question_comment', to='questions.Question')),
            ],
        ),
    ]
