# Generated by Django 2.1.5 on 2019-06-10 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncomment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questiondistractor',
            name='choice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.Choice'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='questiondistractor',
            unique_together={('question_id', 'choice_id')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('user_id', 'question_id')},
        ),
        migrations.AlterUniqueTogether(
            name='questiontag',
            unique_together={('question_id', 'tag_id')},
        ),
    ]
