# Generated by Django 2.2.2 on 2019-07-02 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190702_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='next_due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 4, 17, 46, 179016, tzinfo=utc)),
        ),
    ]
