# Generated by Django 2.1.5 on 2019-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190610_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='stem',
            field=models.TextField(),
        ),
    ]
