# Generated by Django 2.2.2 on 2019-07-03 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190702_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='next_due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 11, 27, 15, 245005, tzinfo=utc)),
        ),
    ]
