# Generated by Django 2.2.2 on 2019-06-25 05:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_auto_20190620_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='domain',
            field=models.IntegerField(choices=[(0, 'GENERAL_DOMAIN'), (1, 'FOUNDATION'), (2, 'ASSESSMENT'), (3, 'INVESTIGATION'), (4, 'DIAGNOSIS'), (5, 'MANAGEMENT')], default=0),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='ease',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='interval_days',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='next_due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 5, 12, 18, 304171)),
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
