# Generated by Django 2.2.2 on 2019-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190615_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondistractor',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
