# Generated by Django 2.2.2 on 2019-06-25 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190625_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='next_due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 5, 13, 22, 64823, tzinfo=utc)),
        ),
    ]
