# Generated by Django 2.2.2 on 2019-07-06 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190703_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='next_due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 14, 37, 10, 744772, tzinfo=utc)),
        ),
    ]
