# Generated by Django 2.2.2 on 2019-06-26 00:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190625_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_response', to='questions.QuestionChoice'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='next_due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 0, 40, 42, 800464, tzinfo=utc)),
        ),
    ]
