# Generated by Django 2.2.2 on 2019-08-20 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190716_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='next_due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 13, 15, 15, 417322, tzinfo=utc)),
        ),
    ]
