# Generated by Django 3.0.1 on 2019-12-29 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation.')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Time of modification.')),
                ('specialty', models.IntegerField(choices=[(0, 'PRINCIPLES'), (1, 'CARDIOVASCULAR'), (2, 'RESPIRATORY'), (3, 'GASTROINTESTINAL'), (4, 'RENAL_AND_UROLOGICAL'), (5, 'MUSCULOSKELETAL_AND_RHEUMATOLOGICAL'), (6, 'NEUROLOGICAL'), (7, 'HAEMATOLOGICAL'), (8, 'ENDOCRINE'), (9, 'MENTAL_AND_BEHAVIOURAL'), (10, 'OBSTETRIC_AND_GYNAECOLOGICAL'), (11, 'OTOLARYNGOLOGICAL'), (12, 'OPHTHALMOLOGICAL'), (13, 'DERMATOLOGICAL')], help_text='The specialty tag for this objective.')),
                ('topic', models.IntegerField(choices=[(0, 'OVERVIEW'), (1, 'GLOBAL_ISSUES'), (2, 'DEVELOPMENT'), (3, 'CELL_LEVEL_STRUCTURE'), (4, 'ORGAN_LEVEL_STRUCTURE'), (5, 'THEORY_OF_NORMAL_FUNCTION'), (6, 'THEORY_OF_ABNORMAL_FUNCTION'), (7, 'MEDICATIONS'), (8, 'CLINICAL_HISTORY'), (9, 'CLINICAL_EXAM'), (10, 'CLINICAL_INVESTIGTIONS'), (11, 'CLINICAL_PROCEDURES'), (12, 'DISORDERS_-_INFECTIOUS'), (13, 'DISORDERS_-_NEOPLASTIC'), (14, 'DISORDERS_-_EMERGENCY'), (15, 'DISORDERS_-_SPECIFIC'), (16, 'DISORDERS_-_PAEDIATRIC'), (17, 'DISORDERS_-_PRIMARY_CARE_&_PREVENTION'), (18, 'DISORDERS_-_TRAUMA_EXTERNAL'), (19, 'MISCELLANEOUS_TOPICS')], help_text='The topic tag for this objective.')),
                ('stage', models.IntegerField(choices=[(0, 'YEAR_1'), (1, 'YEAR_2A'), (2, 'YEAR_3B'), (3, 'YEAR_4C'), (4, 'YEAR_5D'), (5, 'INTERN'), (6, 'RESIDENT'), (7, 'REGISTRAR')], help_text='The medical training stage tag for this objective')),
                ('title', models.CharField(help_text='A brief statement of the objective, no more than 280 characters.', max_length=280, unique=True)),
                ('notes', models.TextField(help_text='The notes for this objective in Markdown.')),
                ('contributor', models.ForeignKey(help_text='The user assigned to this objective for editing and deletion.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
