# Generated by Django 3.0.1 on 2020-01-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='notes',
            field=models.TextField(blank=True, help_text='The notes for this objective in Markdown.', null=True),
        ),
    ]
