# Generated by Django 2.2.2 on 2019-07-02 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.IntegerField(choices=[(0, 'PRINCIPLES'), (1, 'CARDIOVASCULAR'), (2, 'RESPIRATORY'), (3, 'GASTROINTESTINAL'), (4, 'RENAL_AND_UROLOGICAL'), (5, 'MUSCULOSKELETAL_AND_RHEUMATOLOGICAL'), (6, 'NEUROLOGICAL'), (7, 'HAEMATOLOGICAL'), (8, 'ENDOCRINE'), (9, 'MENTAL_AND_BEHAVIOURAL'), (10, 'OBSTETRIC_AND_GYNAECOLOGICAL'), (11, 'OTOLARYNGOLOGICAL'), (12, 'OPHTHALMOLOGICAL'), (13, 'DERMATOLOGICAL')], default=0)),
                ('topic', models.IntegerField(choices=[(0, 'OVERVIEW'), (1, 'GLOBAL_ISSUES'), (2, 'DEVELOPMENT'), (3, 'CELL_LEVEL_STRUCTURE'), (4, 'ORGAN_LEVEL_STRUCTURE'), (5, 'THEORY_OF_NORMAL_FUNCTION'), (6, 'THEORY_OF_ABNORMAL_FUNCTION'), (7, 'MEDICATIONS'), (8, 'CLINICAL_HISTORY'), (9, 'CLINICAL_EXAM'), (10, 'CLINICAL_INVESTIGTIONS'), (11, 'CLINICAL_PROCEDURES'), (12, 'DISORDERS_INFECTIOUS'), (13, 'DISORDERS_NEOPLASTIC'), (14, 'DISORDERS_SPECIFIC_GROUPS'), (15, 'DISORDERS_PAEDIATRIC'), (16, 'DISORDERS_PRIMARY_CARE_PREVENTION'), (17, 'DISORDERS_TRAUMA_EXTERNAL'), (18, 'MISCELLANEOUS_TOPICS')], default=0)),
                ('title', models.CharField(max_length=60, unique=True)),
                ('content', models.TextField()),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('specialty', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='NoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_comment', to='notes.Note')),
            ],
        ),
    ]
