# Generated by Django 2.2.2 on 2019-07-02 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.IntegerField(choices=[(0, 'OVERVIEW'), (1, 'GLOBAL_ISSUES'), (2, 'DEVELOPMENT'), (3, 'CELL_LEVEL_STRUCTURE'), (4, 'ORGAN_LEVEL_STRUCTURE'), (5, 'THEORY_OF_NORMAL_FUNCTION'), (6, 'THEORY_OF_ABNORMAL_FUNCTION'), (7, 'MEDICATIONS'), (8, 'CLINICAL_HISTORY'), (9, 'CLINICAL_EXAM'), (10, 'CLINICAL_INVESTIGTIONS'), (11, 'CLINICAL_PROCEDURES'), (12, 'DISORDERS_-_INFECTIOUS'), (13, 'DISORDERS_-_NEOPLASTIC'), (14, 'DISORDERS_-_SPECIFIC'), (15, 'DISORDERS_-_PAEDIATRIC'), (16, 'DISORDERS_-_PRIMARY_CARE_&_PREVENTION'), (17, 'DISORDERS_-_TRAUMA_EXTERNAL'), (18, 'MISCELLANEOUS_TOPICS')], default=0),
        ),
    ]
