# Generated by Django 2.2.2 on 2019-06-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190620_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='domain',
        ),
    ]
