# Generated by Django 2.2.2 on 2019-07-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190702_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.IntegerField(choices=[(0, 'OVERVIEW'), (1, 'GLOBAL_ISSUES'), (2, 'DEVELOPMENT'), (3, 'CELL_LEVEL_STRUCTURE'), (4, 'ORGAN_LEVEL_STRUCTURE'), (5, 'THEORY_OF_NORMAL_FUNCTION'), (6, 'THEORY_OF_ABNORMAL_FUNCTION'), (7, 'MEDICATIONS'), (8, 'CLINICAL_HISTORY'), (9, 'CLINICAL_EXAM'), (10, 'CLINICAL_INVESTIGTIONS'), (11, 'CLINICAL_PROCEDURES'), (12, 'DISORDERS_-_INFECTIOUS'), (13, 'DISORDERS_-_NEOPLASTIC'), (14, 'DISORDERS_-_EMERGENCY'), (15, 'DISORDERS_-_SPECIFIC'), (16, 'DISORDERS_-_PAEDIATRIC'), (17, 'DISORDERS_-_PRIMARY_CARE_&_PREVENTION'), (18, 'DISORDERS_-_TRAUMA_EXTERNAL'), (19, 'MISCELLANEOUS_TOPICS')], default=0),
        ),
    ]
