# Generated by Django 2.2.2 on 2019-06-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecomment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_comment', to='notes.Note'),
        ),
    ]
