# Generated by Django 2.1.5 on 2019-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80, unique=True)),
                ('category', models.IntegerField(choices=[(0, 'uncategorised'), (1, 'yearLevel'), (2, 'specialty'), (3, 'collection'), (4, 'domain'), (5, 'matrix')])),
            ],
            options={
                'ordering': ('category', 'content'),
            },
        ),
    ]
