# Generated by Django 2.1.5 on 2019-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(unique=True)),
                ('category', models.IntegerField(choices=[(0, 'uncategorised'), (1, 'symptom'), (2, 'sign'), (3, 'diagnosis'), (4, 'investigation'), (5, 'medication'), (6, 'intervention'), (7, 'pathogen'), (8, 'vaccine')])),
            ],
            options={
                'ordering': ('category', 'content'),
            },
        ),
    ]
